# Generated by Django 3.2.9 on 2021-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/blog/categories/', verbose_name='Фото категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Слоган категории'),
        ),
    ]
